stages:
    - build
    - test
    - clean

build:
    stage: build
    artifacts:
        paths:
            - venv
            - panem.egg-info
    script:
        - make venv dev

test:
    stage: test
    script:
        - make test

down:
    stage: clean
    script:
        - make down
