stages:
    - build
    - test

build:
    stage: build
    artifacts:
        paths:
            - venv
            - panem.egg-info
    script:
        - make venv dev

test:
    stage: test
    script:
        - make test
