version: '3'

services:
    postgres:
        image: postgres:9.6
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    web:
        image: python:3.5
        ports: ['5000:5000']
        environment:
            TESTING: testing
            WEBHOOK_URL: http://webhook.test
            WEBHOOK_API_KEY: rick
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            API_KEY: ${API_KEY}
            PANEM_CONFIG: ${PANEM_CONFIG}
            LISTEN: 0.0.0.0
            PORT: 5000
        volumes:
            - .:/opt/panem
        working_dir: /opt/panem

        command: ./venv/Linux/bin/panem-web
