version: '3'

services:
    postgres:
        image: postgres:9.6
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    web:
        image: bearstech/python-dev:3
        ports: ['5000:5000']
        environment:
            TESTING: testing
            WEBHOOK_URL: http://webhook.test
            FLASK_APP: panem.app
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            API_KEY: ${API_KEY}
        volumes:
            - ./:/opt/panem
        working_dir: /opt/panem

        command: venv/bin/python -m flask run -h 0.0.0.0 -p 5000
